"""Deterministic Flask-test facade over a real FastAPI/Starlette application."""

import importlib.util
import sys
from pathlib import Path

import click
import pytest
from fastapi import FastAPI, Request
from starlette.middleware.sessions import SessionMiddleware

from portage_agent.recipes.flask_test_compat import render_flask_test_compat


@pytest.fixture
def compat(tmp_path: Path):
    path = tmp_path / "_portage_fastapi_test_compat.py"
    path.write_text(render_flask_test_compat())
    spec = importlib.util.spec_from_file_location("_portage_fastapi_test_compat", path)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def _app() -> FastAPI:
    app = FastAPI()
    app.state.config = {"TESTING": True, "SECRET_KEY": "test-secret"}
    app.add_middleware(SessionMiddleware, secret_key="test-secret")

    @app.get("/json")
    def json_route():
        return {"ok": True}

    @app.get("/session")
    def session_route(request: Request):
        return dict(request.session)

    return app


def test_client_response_config_and_context_facades(compat):
    wrapped = compat.adapt_app(_app(), instance_path="/tmp/instance")
    assert wrapped.config["TESTING"] is True
    assert wrapped.testing is True
    assert wrapped.instance_path == "/tmp/instance"
    with wrapped.app_context() as active:
        assert active is wrapped
    with wrapped.test_client() as client:
        response = client.get("/json")
        assert response.status_code == 200
        assert response.get_json() == {"ok": True}
        assert response.get_data(as_text=True)
        assert response.data


def test_cli_runner_preserves_flask_invoke_shape(compat):
    @click.command("hello")
    @click.option("--name", default="world")
    def hello(name):
        click.echo(f"hello {name}")

    wrapped = compat.adapt_app(_app(), commands={"hello": hello})
    result = wrapped.test_cli_runner().invoke(args=["hello", "--name", "portage"])
    assert result.exit_code == 0
    assert result.output.strip() == "hello portage"


def test_session_transaction_round_trip(compat):
    wrapped = compat.adapt_app(_app())
    client = wrapped.test_client()
    with client.session_transaction() as session:
        session["user_id"] = 7
    assert client.get("/session").get_json() == {"user_id": 7}
    with client.session_transaction() as session:
        session.clear()
    assert client.get("/session").get_json() == {}


def test_session_transaction_without_middleware_is_explicitly_unsupported(compat):
    client = compat.adapt_app(FastAPI()).test_client()
    with pytest.raises(compat.UnsupportedTestSeam, match="SessionMiddleware"):
        with client.session_transaction():
            pass


def test_rendered_module_has_ownership_marker():
    assert render_flask_test_compat().startswith("# Generated by Portage")
