"""Renderer for Portage's deterministic, repo-local Flask test compatibility facade."""

from __future__ import annotations

import textwrap

_SOURCE = r'''
# Generated by Portage. Test-only FastAPI facade; do not use in production code.
from __future__ import annotations

import json
from base64 import b64decode, b64encode
from contextlib import contextmanager

import itsdangerous
from click.testing import CliRunner
from fastapi.testclient import TestClient


class UnsupportedTestSeam(RuntimeError):
    pass


class FlaskResponseAdapter:
    def __init__(self, response):
        self._response = response

    def __getattr__(self, name):
        return getattr(self._response, name)

    @property
    def data(self):
        return self._response.content

    def get_json(self):
        return self._response.json()

    def get_data(self, as_text=False):
        return self._response.text if as_text else self._response.content


class FlaskCliRunnerAdapter:
    def __init__(self, commands):
        self._commands = dict(commands or {})

    def invoke(self, cli=None, args=None, **kwargs):
        values = list(args or [])
        command = cli
        if command is None:
            if not values or values[0] not in self._commands:
                raise UnsupportedTestSeam("unknown Click command in invoke(args=[...])")
            command = self._commands[values.pop(0)]
        return CliRunner().invoke(command, args=values, **kwargs)


class FlaskClientAdapter:
    def __init__(self, app):
        self._app = app
        self._client = TestClient(app)

    def __enter__(self):
        self._client.__enter__()
        return self

    def __exit__(self, *args):
        return self._client.__exit__(*args)

    def __getattr__(self, name):
        return getattr(self._client, name)

    def request(self, *args, **kwargs):
        return FlaskResponseAdapter(self._client.request(*args, **kwargs))

    def get(self, *args, **kwargs):
        return FlaskResponseAdapter(self._client.get(*args, **kwargs))

    def post(self, *args, **kwargs):
        return FlaskResponseAdapter(self._client.post(*args, **kwargs))

    def put(self, *args, **kwargs):
        return FlaskResponseAdapter(self._client.put(*args, **kwargs))

    def patch(self, *args, **kwargs):
        return FlaskResponseAdapter(self._client.patch(*args, **kwargs))

    def delete(self, *args, **kwargs):
        return FlaskResponseAdapter(self._client.delete(*args, **kwargs))

    def head(self, *args, **kwargs):
        return FlaskResponseAdapter(self._client.head(*args, **kwargs))

    def options(self, *args, **kwargs):
        return FlaskResponseAdapter(self._client.options(*args, **kwargs))

    def _session_config(self):
        for middleware in self._app.user_middleware:
            if middleware.cls.__name__ == "SessionMiddleware":
                kwargs = dict(middleware.kwargs)
                return {
                    "secret_key": str(kwargs["secret_key"]),
                    "cookie": kwargs.get("session_cookie", "session"),
                    "path": kwargs.get("path", "/"),
                    "max_age": kwargs.get("max_age", 14 * 24 * 60 * 60),
                }
        raise UnsupportedTestSeam("session_transaction requires SessionMiddleware")

    @contextmanager
    def session_transaction(self):
        config = self._session_config()
        signer = itsdangerous.TimestampSigner(config["secret_key"])
        raw = self._client.cookies.get(config["cookie"])
        session = {}
        if raw:
            try:
                payload = signer.unsign(raw.encode(), max_age=config["max_age"])
                session = json.loads(b64decode(payload))
            except itsdangerous.BadSignature:
                session = {}
        yield session
        if session:
            payload = b64encode(json.dumps(session).encode())
            value = signer.sign(payload).decode()
            self._client.cookies.set(config["cookie"], value, path=config["path"])
        else:
            self._client.cookies.delete(config["cookie"], path=config["path"])


class FastAPITestAdapter:
    def __init__(self, app, commands=None, instance_path=None):
        self._app = app
        self._commands = dict(commands or {})
        self._instance_path = instance_path

    def __getattr__(self, name):
        return getattr(self._app, name)

    @property
    def config(self):
        return self._app.state.config

    @property
    def testing(self):
        return bool(self.config.get("TESTING", False))

    @property
    def instance_path(self):
        if self._instance_path is None:
            raise UnsupportedTestSeam("instance_path was not supplied to adapt_app")
        return self._instance_path

    @contextmanager
    def app_context(self):
        yield self

    def test_client(self):
        return FlaskClientAdapter(self._app)

    def test_cli_runner(self):
        return FlaskCliRunnerAdapter(self._commands)


def adapt_app(app, *, commands=None, instance_path=None):
    return FastAPITestAdapter(app, commands=commands, instance_path=instance_path)
'''


def render_flask_test_compat() -> str:
    return textwrap.dedent(_SOURCE).lstrip()
